# NUMPY NOTES

NUMPY:- Numeriacal python i.e numerical computation

Data manupulation is process of conerting data into format that is easy to read abd more organised

https://www.w3resource.com/python-exercises/numpy/index.php

https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution

In [164]:
pip install numpy

In [2]:
import numpy as np

In [167]:
np.version.version

'1.26.2'

In [169]:
#!pip install --upgrade numpy

In [180]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [181]:
len(dir(np))

591

In [182]:
np.__version__

'1.26.2'

In [ ]:
np.info(np.dtype)  # view the documentation --info()

Different way of creating array

In [488]:
a = np.array([1,2,2,3,4]) #1D array
a

array([1, 2, 2, 3, 4])

In [184]:
type(a)

numpy.ndarray

In [171]:
a[0]

1

In [173]:
a[-2]

3

In [491]:
b = a.tolist()  #coverting array to list
b

[1, 2, 2, 3, 4]

In [185]:
import numpy as np

a = np.array({1,1,2,23,23,2,3,4,5,67,67,7,7,7,7})
print(a)
type(a)

{1, 2, 3, 4, 5, 67, 7, 23}


numpy.ndarray

In [189]:
a = np.array({1:100,2:200,3:300})
print(a)
print(type(a))
print(a.dtype)

{1: 100, 2: 200, 3: 300}
<class 'numpy.ndarray'>
object


In [190]:
#creating empty array
a = np.array([])
a

array([], dtype=float64)

In [191]:
print(a)

[]


In [194]:
type(a)

numpy.ndarray

In [195]:
a.dtype

dtype('float64')

In [199]:
z = np.zeros((2,3))
print(z)
print(type (z))
z

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


array([[0., 0., 0.],
       [0., 0., 0.]])

In [201]:
o = np.ones((2,3))
print(o)
type(o)

[[1. 1. 1.]
 [1. 1. 1.]]


numpy.ndarray

In [466]:
a = np.empty((2,2))  # creating empty array
a

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [9]:
# Random numbers generated between 0 to 1 each time run
np.random.random((2,2))

array([[0.62151748, 0.54362706],
       [0.30170784, 0.90776888]])

In [227]:
np.random.random(5)

array([0.18828443, 0.42489891, 0.94498565, 0.79624164, 0.57142603])

In [467]:
q = np.random.random((2,5))
q

array([[0.84167   , 0.35739757, 0.04359146, 0.30476807, 0.39818568],
       [0.70495883, 0.99535848, 0.35591487, 0.76254781, 0.59317692]])

In [468]:
#array inspection
print(q.shape)
print(q.size)
print(q.ndim)
print(q.dtype)
print(type(q))
print(len(q))

(2, 5)
10
2
float64
<class 'numpy.ndarray'>
2


In [469]:
q.astype(int) #Converts to Data Type

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [3]:
aa = np.random.normal(10,2, (2,2))
aa

array([[14.99803025,  9.93274632],
       [10.57320444, 11.62160203]])

In [4]:
ww = np.random.randint(10,200)
ww

101

In [6]:
ww = np.random.randint(10,200,(3,3))
ww

array([[102,  27, 179],
       [143,  72, 151],
       [ 93,  64, 152]])

Difference between creating and intialising array, while creating it can be empty as well but when intialising we are actually entering values in array

 array initialisation

In [10]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [215]:
f = np.full((2,3),'red')
print(f)

[['red' 'red' 'red']
 ['red' 'red' 'red']]


In [492]:
f.flatten()  #Flattens 2D array two_d_arr to 1D

array(['red', 'red', 'red', 'red', 'red', 'red'], dtype='<U3')

In [493]:
f.T  #transpose matrix

array([['red', 'red'],
       ['red', 'red'],
       ['red', 'red']], dtype='<U3')

In [495]:
f.transpose()

array([['red', 'red'],
       ['red', 'red'],
       ['red', 'red']], dtype='<U3')

In [501]:
aa = np.arange(15).reshape(5,3)
aa

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [503]:
d = np.delete(aa,2,axis=0) #row delete
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [12, 13, 14]])

In [504]:
d1 = np.delete(aa,2,axis=1)   #column delete
d1 

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [524]:
aa = np.arange(5,10)
aa

array([5, 6, 7, 8, 9])

In [525]:
np.append(aa,1)
aa

array([5, 6, 7, 8, 9])

In [523]:
aa

array([5, 6, 7, 8, 9])

**Shallow Copy** - creates a new array object however the data is still shared between the original and the copy. Whatever the changes made to the data in one array will affect the other

In [7]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
a2 = a1.view()
a2

array([1, 2, 3])

In [10]:
a1[0]=10
a1

array([10,  2,  3])

In [11]:
a2

array([10,  2,  3])

**Arrays are mutable means data can be modified**

**Deep Copy** - creates a completely new array object with its own copy of the data. Changes in one array will not affect the other

In [13]:
a3 = a1.copy()  #np.copy(a1)
a3

array([10,  2,  3])

In [19]:
a1[0]=20
a1,a2

(array([20,  2,  3]), array([20,  2,  3]))

In [20]:
a3

array([30,  2,  3])

In [17]:
a3[0]=30
a3

array([30,  2,  3])

In [18]:
a1

array([20,  2,  3])

**Direct Assignment**: this is equivalent to a shallow copy which basically means reference to the same data

In [21]:
a4 = a1
a4

array([20,  2,  3])

In [22]:
a1[1]=80
a1

array([20, 80,  3])

In [23]:
a4

array([20, 80,  3])

**Conclusion: Shallow copies or direct assignments do not create a new array in the memory hence it's memory efficient**

In [12]:
# Arange - (start, stop, stepsize)
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [261]:
aa = np.arange(0,100,10)
aa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [262]:
aa.size

10

In [265]:
aa.reshape(2,5)  # doesnt chnage originL
aa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [266]:
aa.resize(2,5)  #chnage orignal 
aa

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [14]:
# Linspace - Generates equally spaced numbers 
np.linspace(5,10,3)

array([ 5. ,  7.5, 10. ])

In [61]:
np.linspace(10,50,retstep=True) #by default it generates 50 values

(array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
        14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
        18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
        22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
        26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
        30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
        34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
        38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
        42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
        46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ]),
 0.8163265306122449)

In [221]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [174]:
# u stands for unicode ( it created whenever we use string data )
# unicode is a standardised character encoding system
alph = np.array(['a',2,'c'])

In [175]:
alph

array(['a', '2', 'c'], dtype='<U11')

In [176]:
alph.dtype

dtype('<U11')

In [15]:
a = np.array([[1,2,3,4],[5,2,6,9]])   # 2 D array
a

array([[1, 2, 3, 4],
       [5, 2, 6, 9]])

In [16]:
a.shape

(2, 4)

In [17]:
a.size

8

In [18]:
a.ndim    # number of dimension

2

In [19]:
a.dtype

dtype('int32')

In [20]:
a.shape =(4,2) # resizing array
a

array([[1, 2],
       [3, 4],
       [5, 2],
       [6, 9]])

resize()

- returns a **new** array with the specified shape
- if the new array is larger than the original array, the new array is going to be filled with the repeated copies of the original array

In [24]:
b = np.arange(24)
b.size

24

In [27]:
b.ndim

1

In [31]:
b.shape

(24,)

In [34]:
b.resize(3,4,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [35]:
b.shape

(3, 4, 2)

In [37]:
b.shape=(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
b.size #it give number of element in array

24

In [40]:
b.dtype

dtype('int32')

In [48]:
b.resize(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
a = np.array([[1,2],[3,4]])

In [63]:
np.resize(a, (3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

In [64]:
np.resize(a, (3,3,3))

array([[[1, 2, 3],
        [4, 1, 2],
        [3, 4, 1]],

       [[2, 3, 4],
        [1, 2, 3],
        [4, 1, 2]],

       [[3, 4, 1],
        [2, 3, 4],
        [1, 2, 3]]])

reshape()

- is used to a give a new shape to an array `without changing its data/elements`
- the new shape must be compatible with the original shape

In [379]:
c = np.arange(12, dtype = float)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [380]:
print(c.size)
print(c.dtype)
print(c.ndim)
print(c.shape)

12
float64
1
(12,)


In [381]:
c.resize(3,4)
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [382]:
c.reshape(2,2,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [383]:
np.reshape(c,(3,2,2))

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]]])

In [70]:
c.shape=(3,2,2)
c

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]]])

In [72]:
print(c.size)
print(c.dtype)
print(c.ndim)
print(c.shape)

12
float64
3
(3, 2, 2)


In [79]:
c.dtype

dtype('float64')

In [80]:
c.dtype = int

In [81]:
c.dtype

dtype('int32')

In [178]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3D array
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [179]:
print(a.size)
print(a.dtype)
print(a.ndim)
print(a.shape)

9
int32
3
(1, 3, 3)


In [373]:
xx = np.identity(3)
xx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [374]:
x = np.edentity(2,3)

AttributeError: module 'numpy' has no attribute 'edentity'

In [376]:
x = np.eye(2,3)
x

array([[1., 0., 0.],
       [0., 1., 0.]])

In [204]:
aa = np.eye(3)
print(aa)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [206]:
z = np.eye(2)
z

array([[1., 0.],
       [0., 1.]])

In [209]:
d = np.diag(np.array([1,2,3,4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [211]:
f = np.full((2,3),66)
f

array([[66, 66, 66],
       [66, 66, 66]])

In [470]:
f = np.full((2,3),'red')
print(f)
f

[['red' 'red' 'red']
 ['red' 'red' 'red']]


array([['red', 'red', 'red'],
       ['red', 'red', 'red']], dtype='<U3')

In [244]:
# Reshape - It doesnot change the original array

ls = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ls)
print("--------------------------------")
print(ls.reshape(4,3))
print("--------------------------------")
print(ls)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [245]:
# Resize - It changes the original array 

ls = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ls)
print("--------------------------------")
print(ls.resize(4,3))
print("--------------------------------")
print(ls)
ls.ndim

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------------------
None
--------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

In [267]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [271]:
c = a.reshape(2,4,3)
print(c)
c.ndim

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


3

In [370]:
## The dimension of the array ( 1D, 2D, 3D.. )
#print(arr.ndim)
print("---------------------------")

r = np.array([2,2,2])
print(r)
print(r.ndim)

print("---------------------------")
rr = np.array([[2,2,2],[3,3,3]])
print(rr)
print(rr.ndim)

print("---------------------------")
rrr = np.array([[[2,2,2],[3,3,3],[4,4,4]]])
print(rrr)
print(rrr.ndim)

---------------------------
[2 2 2]
1
---------------------------
[[2 2 2]
 [3 3 3]]
2
---------------------------
[[[2 2 2]
  [3 3 3]
  [4 4 4]]]
3


In [371]:
arr3=np.array([1,2,3],dtype='str')
print(arr3)
print(arr3.dtype)
type(arr3)

['1' '2' '3']
<U1


numpy.ndarray

In [372]:
import numpy as np #import the numpy

arr1=np.array([1,2,3],dtype='int')
print(arr1.dtype)

arr2=np.array([1,2,3],dtype='float')
print(arr2.dtype)

int32
float64


In [377]:
np.random.randint(0,100,25)

array([97, 76, 40,  3, 69, 64, 75, 34, 58, 10, 22, 77, 18, 15, 27, 30, 52,
       70, 26, 80,  6, 14, 75, 54, 71])

In [378]:
np.random.randint(low=0,high=100,size=25)

array([ 1, 43, 58, 55, 25, 50, 84, 56, 49, 12, 18, 81,  1, 51, 44, 48, 56,
       91, 49, 86,  3, 67, 11, 21, 89])

In [384]:
rand_arr = np.arange(0, 1000, 2)
rand_arr2=np.random.choice(rand_arr,50)
rand_arr2

array([206, 978, 708,   6, 790, 518, 486, 444, 524, 530, 174,  28, 972,
       934, 754, 396, 280, 876,  54, 588, 802, 890, 732, 660, 710, 232,
       198, 386, 606, 986,  32, 266, 720, 218, 172,  92, 542, 630, 592,
       818, 602, 866, 512, 838, 826, 770, 934, 648, 828, 782])

In [388]:
arrr=np.array([1,2,3,4,5])
print(np.where(arrr==4))

(array([3], dtype=int64),)


In [387]:
5 in arrr

True

In [389]:
import numpy as np

ak_arr = np.array([1, 2, 3,4, 5])

#a)
ak_arr = np.append(ak_arr, 6)
print(ak_arr)

#b)
ak_arr = np.insert(ak_arr, 0, 10)
print(ak_arr)
#c)
ak_arr = np.insert(ak_arr, 4, 30)
print(ak_arr)

#d)
#Naive approch we avoid
ak_arr[4]=50
print(ak_arr)

#e)
# ak_arr.pop()
# Good approach
ak_arr = np.delete(ak_arr,np.where(ak_arr== 50)[0][0])
print(ak_arr)

[1 2 3 4 5 6]
[10  1  2  3  4  5  6]
[10  1  2  3 30  4  5  6]
[10  1  2  3 50  4  5  6]
[10  1  2  3  4  5  6]


In [390]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [391]:
np.delete(a,1)   # delete with position

array([1, 3, 4, 5, 6, 7])

In [472]:
aa=np.array(['red',9,63,True])
aa

array(['red', '9', '63', 'True'], dtype='<U11')

In [473]:
dd = np.copy(aa)   #	Creates copy of array
dd

array(['red', '9', '63', 'True'], dtype='<U11')

In [477]:
ww = np.array([6,9,2,7,-3,4,12,7])
ww

array([ 6,  9,  2,  7, -3,  4, 12,  7])

In [482]:
ww.sort()
ww

array([-3,  2,  4,  6,  7,  7,  9, 12])

# maths op

In [483]:
a, b = 10,12

In [87]:
a+b

22

In [272]:
np.sum([10,12,20,32])

74

In [89]:
np.sum([a,b])

22

In [101]:
a = np.array([[1,2],[3,4]])

In [104]:
np.sum(a)

10

In [105]:
np.sum(a, axis = 0)

array([4, 6])

In [107]:
np.sum(a, axis = 1)

array([3, 7])

In [98]:
np.sum([[0,1],[0,5]])

6

In [99]:
np.sum([[0,1],[0,5]], axis = 0)  # row add

array([0, 6])

In [100]:
np.sum([[0,1],[0,5]], axis = 1)#column add

array([1, 5])

In [28]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
np.add(a,5)

array([6, 7, 8])

In [30]:
a+5

array([6, 7, 8])

In [31]:
aa = [1,2,3]
type(aa)

list

In [32]:
aa+5

TypeError: can only concatenate list (not "int") to list

In [33]:
aa+[5]  # concatenation

[1, 2, 3, 5]

In [37]:
b = np.array([4,9,16], dtype=int)
np.sqrt(b)

array([2., 3., 4.])

In [38]:
np.floor_divide(a,2)

array([0, 1, 1], dtype=int32)

In [40]:
np.negative(a)

array([-1, -2, -3])

In [41]:
np.mod(a,3)  # modulus i.r reminder

array([1, 2, 0], dtype=int32)

In [108]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]

In [109]:
# element wise comparison
np.equal(a,b)

array([False, False,  True])

In [110]:
np.equal(a,c)

array([ True,  True,  True])

In [111]:
#array wise comparison
np.array_equal(a,b)

False

In [112]:
np.array_equal(a,c)

True

In [282]:
# Create 2 random numpy arrays of 3X4 and compare element by element 

a = np.random.random([3,4])
b = np.random.random([3,4])
print(a)
print(b)
print(np.equal(a,b))

[[0.42226786 0.69466268 0.68452417 0.80469788]
 [0.03592232 0.50387737 0.63774462 0.29174572]
 [0.3026473  0.17426498 0.52231427 0.18052756]]
[[0.29230066 0.88657275 0.48654826 0.90776814]
 [0.00769795 0.21100705 0.88667792 0.86360961]
 [0.82852928 0.2391231  0.98534595 0.78858441]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [285]:
# Generate similar random numbers 

np.random.seed(1234)
a = np.random.random([3,4])
print(a)

[[0.19151945 0.62210877 0.43772774 0.78535858]
 [0.77997581 0.27259261 0.27646426 0.80187218]
 [0.95813935 0.87593263 0.35781727 0.50099513]]


In [286]:
# Create 2 random numpy arrays of 3X4 with SAME SEED and compare element by element 

np.random.seed(123)
a = np.random.random([3,4])

np.random.seed(123)
b = np.random.random([3,4])

print(a)
print(b)
np.equal(a,b)

[[0.69646919 0.28613933 0.22685145 0.55131477]
 [0.71946897 0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802 0.72904971]]
[[0.69646919 0.28613933 0.22685145 0.55131477]
 [0.71946897 0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802 0.72904971]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [294]:
import numpy as np
a =np.array([1,2,4])
print(type(a))
print(np.sum(a))  #array wise sum
print(np.min(a))  #min of array
print(np.max(a))   #max of array
print(np.mean(a))   #mean of array
print(np.median(a))    #median of array
print(np.corrcoef(a))   #correlation coefficient of array
print(np.std(a))   # std of array


# print(np.mode(a))   module 'numpy' has no attribute 'mode'


<class 'numpy.ndarray'>
7
1
4
2.3333333333333335
2.0
1.0
1.247219128924647


In [295]:
import numpy as np
a = [1,2,4]
print(type(a))
print(np.sum(a))  #array wise sum
print(np.min(a))  #min of array
print(np.max(a))   #max of array
print(np.mean(a))   #mean of array
print(np.median(a))    #median of array
print(np.corrcoef(a))   #correlation coefficient of array
print(np.std(a))   # std of array

<class 'list'>
7
1
4
2.3333333333333335
2.0
1.0
1.247219128924647


In [129]:
a = ([[[1,2,3],[4,5,6],[7,8,9]]])
a
print(type(a))
print(len(a))

<class 'list'>
1


In [273]:
print(np.array([[10,20],[10,20]]))

print(np.sum([[10,20],[10,20]]))

[[10 20]
 [10 20]]
60


In [274]:
print(np.array([[10,20],[10,20]]))
print('_'*50)
print(np.sum([[10,20],[10,20]], axis = 0))  # ROw wise addition

[[10 20]
 [10 20]]
__________________________________________________
[20 40]


In [275]:
print(np.array([[10,20],[10,20]]))
print("-"*50)
print(np.sum([[10,20],[10,20]], axis = 1))  # Column wise addition

[[10 20]
 [10 20]]
--------------------------------------------------
[30 30]


In [277]:
np.subtract([10,20],[20,30])

array([-10, -10])

In [279]:
np.multiply([10,20],[20,30]) # element wise multiplication

array([200, 600])

In [281]:
np.divide([10,20],[20,30])

array([0.5       , 0.66666667])

In [368]:
a = np.array([1,2,3,4])
b = np. array([10,20,30,40])

print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [369]:
print([a]+[b]) 
print([a],[b])

[array([1, 2, 3, 4]), array([10, 20, 30, 40])]
[array([1, 2, 3, 4])] [array([10, 20, 30, 40])]


In [423]:
a =np.array ([[1,2],[3,4]])
b =np.array ([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [422]:
a+b

array([[ 6,  8],
       [10, 12]])

In [424]:
a-b

array([[-4, -4],
       [-4, -4]])

In [425]:
a*b # element wise

array([[ 5, 12],
       [21, 32]])

In [426]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [427]:
np.dot(a,b)  # cross multiplication

array([[19, 22],
       [43, 50]])

In [428]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [42]:
scores = np.array([10,20,15,20,12,15,8,5,13,17]) #10 students python scores out of 20 marks

In [54]:
scores.sum()#,np.sum(scores)

(135, 135)

In [52]:
scores.max()#,np.max(scores)

(20, 20)

In [45]:
scores.min()#,np.min(scores)

5

In [56]:
scores.mean()#,np.mean(scores)

13.5

In [47]:
scores.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [48]:
np.median(scores)

14.0

In [49]:
scores.var()#,np.var(scores)

21.85

In [60]:
scores.std()#,np.std(scores)

(4.674398357008098, 4.674398357008098)

In [392]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
z[z%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [393]:
z[z%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [397]:
z=np.arange(20)
z[z%2==1]== 13

array([False, False, False, False, False, False,  True, False, False,
       False])

In [399]:
z = np.arange(20)
x = z.copy()
x[x%2==1]=10
print(x)


[ 0 10  2 10  4 10  6 10  8 10 10 10 12 10 14 10 16 10 18 10]


In [400]:
arr = np.arange(10)
arr.reshape(2, -1) 
# Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [401]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [404]:
a = np.repeat(99,3)
a

array([99, 99, 99])

In [405]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [144]:
#slicing
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(a.dtype)
print(a.size)
print(a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
int32
9
3


In [136]:
a[0][1]

array([4, 5, 6])

In [139]:
a[0][2]

array([7, 8, 9])

In [143]:
a[0:1,0:1,0:1]

array([[[1]]])

In [145]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.dtype)
print(a.size)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
9
2


In [148]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [149]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [151]:
a[2,2]

9

In [152]:
a[1,:2]

array([4, 5])

In [296]:
# Slicilng - Method of accessing elements of a array - 1D and 2D
#syntax := [start:stop:step]
import numpy as np

ls = np.array(['S','A','N','F','R','A','N','C','I','S','C','O'])
ls

array(['S', 'A', 'N', 'F', 'R', 'A', 'N', 'C', 'I', 'S', 'C', 'O'],
      dtype='<U1')

In [297]:
ls[:]

array(['S', 'A', 'N', 'F', 'R', 'A', 'N', 'C', 'I', 'S', 'C', 'O'],
      dtype='<U1')

1D slicing

In [298]:
ls[4:8]

array(['R', 'A', 'N', 'C'], dtype='<U1')

In [299]:
ls[-8:-5]

array(['R', 'A', 'N'], dtype='<U1')

In [300]:
ls[7:]

array(['C', 'I', 'S', 'C', 'O'], dtype='<U1')

In [302]:
ls[-5:]

array(['C', 'I', 'S', 'C', 'O'], dtype='<U1')

In [303]:
ls[-5:12]

array(['C', 'I', 'S', 'C', 'O'], dtype='<U1')

In [304]:
ls[ : : 2]

array(['S', 'N', 'R', 'N', 'I', 'C'], dtype='<U1')

In [305]:
ls[: : 3]

array(['S', 'F', 'N', 'S'], dtype='<U1')

In [308]:
ls[:: -1]  # reversing sequence

array(['O', 'C', 'S', 'I', 'C', 'N', 'A', 'R', 'F', 'N', 'A', 'S'],
      dtype='<U1')

In [309]:
ls[:: -2] 

array(['O', 'S', 'C', 'A', 'F', 'A'], dtype='<U1')

2D slicing

In [310]:
l = np.array(['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P'])
l

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P'], dtype='<U1')

In [311]:
l.size

16

In [317]:
l.shape = (4,4)
print(l)
l.ndim

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'J' 'K' 'L']
 ['M' 'N' 'O' 'P']]


2

In [319]:
#[row[strat:stop:step],column[start:stop:step]]
l[ : , :]

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P']], dtype='<U1')

In [321]:
l[0:2,0:2]

array([['A', 'B'],
       ['E', 'F']], dtype='<U1')

In [322]:
l[0:1,0:1]

array([['A']], dtype='<U1')

In [324]:
l[0][0]

'A'

In [325]:
l[-4:-3,-4:-3]

array([['A']], dtype='<U1')

In [326]:
l[ : ,1:2]

array([['B'],
       ['F'],
       ['J'],
       ['N']], dtype='<U1')

In [327]:
l[:,-3:-2]

array([['B'],
       ['F'],
       ['J'],
       ['N']], dtype='<U1')

In [328]:
l[1:2]

array([['E', 'F', 'G', 'H']], dtype='<U1')

In [329]:
l[1:2,:]

array([['E', 'F', 'G', 'H']], dtype='<U1')

In [330]:
l[-3:-2,:]

array([['E', 'F', 'G', 'H']], dtype='<U1')

In [332]:
l[1:3,1:3]

array([['F', 'G'],
       ['J', 'K']], dtype='<U1')

In [333]:
l[-3:-1,-3:-1]

array([['F', 'G'],
       ['J', 'K']], dtype='<U1')

In [334]:
# Array manipulation 

# Concatination 

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a)
print(b)

print(np.concatenate((a,b)))

# Axis 
print(np.concatenate((a,b), axis = 0))

#print(np.concatenate((a,b), axis = 1)) #Not supported in 1D

[1 2 3 4]
[10 20 30 40]
[ 1  2  3  4 10 20 30 40]
[ 1  2  3  4 10 20 30 40]


In [350]:
a = np.arange(9)
a.shape = (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [349]:
b = np.arange(11,20,1)
b.shape = (3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [353]:
c = np.concatenate((a,b))
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [356]:
c.ndim

2

In [357]:
c = np.concatenate((a,b), axis = 0)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [358]:
c = np.concatenate((a,b), axis = 1)
c

array([[ 0,  1,  2, 11, 12, 13],
       [ 3,  4,  5, 14, 15, 16],
       [ 6,  7,  8, 17, 18, 19]])

In [359]:
x = np.array([1,2,3,4])
y = np.array([10,20,30,40])

In [360]:
# Vertical stack
np.vstack((x,y))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [361]:
# Horizontal stack 
np.hstack((x,y))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [362]:
# Column stack 
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [364]:
zz =np.random.random((4,4))
zz

array([[0.43857224, 0.0596779 , 0.39804426, 0.73799541],
       [0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866, 0.22826323]])

In [366]:
#Hsplit
np.hsplit(zz,2)

[array([[0.43857224, 0.0596779 ],
        [0.18249173, 0.17545176],
        [0.63440096, 0.84943179],
        [0.72244338, 0.32295891]]),
 array([[0.39804426, 0.73799541],
        [0.53155137, 0.53182759],
        [0.72445532, 0.61102351],
        [0.36178866, 0.22826323]])]

In [367]:
#Vsplit
np.vsplit(zz,2)

[array([[0.43857224, 0.0596779 , 0.39804426, 0.73799541],
        [0.18249173, 0.17545176, 0.53155137, 0.53182759]]),
 array([[0.63440096, 0.84943179, 0.72445532, 0.61102351],
        [0.72244338, 0.32295891, 0.36178866, 0.22826323]])]

In [16]:
import numpy as np
x = np.arange(16).reshape(4,4)
print(x, '\n\n')
print(np.hsplit(x,2))
print(np.hsplit(x,np.array([3])),"\n")
print(np.hsplit(x,np.array([2,3])),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 



In [406]:
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [407]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [408]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [409]:
np.resize(a,(5,6)) #if size given more than no of element then those same elemernt repeat again and again

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [410]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [411]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [414]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [415]:
A= np.linspace(1,10) # if we didnt specifie how many number we what it give default 50 values
A

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [416]:
#linspace(start,stop,count, endpoint=True)
A= np.linspace(1,5,10)
A

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [449]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]],dtype=float)
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [450]:
arr.ravel()   # it used to flatten the matrix

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [451]:
arr # raval didnt change the original array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [453]:
arr.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [454]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [429]:
a =np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [435]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [437]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [441]:
a[b] = -10
a

array([[  0,   1,   2,   3],
       [  4, -10, -10, -10],
       [-10, -10, -10, -10]])

In [444]:
a = np.arange(12).reshape(3,4)
print(a)
a[a<4] = 55
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[55, 55, 55, 55],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [447]:
a = np.arange(12).reshape(3,4)
print(a)
a[a<4]  ## we extract element with condition

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [448]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [460]:
a = np.array([20],ndmin=4)  # giving dimension
a

array([[[[20]]]])

In [461]:
a.ndim

4

In [462]:
a = np.array([10,3,1,203,404,204,20,302,30,402,192])
b = np.array([1,2,3,4])

In [463]:
np.insert(a,4,b)

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

# Scipy

In [18]:
!pip install scipy

- scipy built over numpy to make scitific calculation more efficient
- used to scientific n technical computing

In [20]:
import scipy as sc

In [21]:
dir(sc)  # scipy packeges used to compute

['LowLevelCallable',
 '__version__',
 'cluster',
 'constants',
 'datasets',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'misc',
 'ndimage',
 'odr',
 'optimize',
 'show_config',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'test']

**scipy.cluster**
- its used to divide data into cluster based on some attributes
- provides kmeans() function
- Divide n observations into k clusters

- **clustering**: is the process of groupping similar items into one single group
    
    

**how to find cluster**

- step1: randomly select 2 cluster centers
- step2: assign members(data) to the cluster
- step3: calculate mead distance of each member in cluster
- step4: shift the cluster center towards mean
- step5: repear step2 & 3 until no member changes the group

In [24]:
import pandas as pd 
df = pd.read_csv("F:/Course pdf/3.Pandas/class/mtcars2.csv")
df.head(1)

S.No Unnamed: 1   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  \
0     1  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4   

   carb  
0     4

scipy.stats()


**scipy.signal()**

- used for signal processing(1D and periodic signals)
- it basically resamples data pts by usinf FFT(fast fouries transformation)

In [ ]:
scipy.stats()
scipy.optimize()
scipy.integrate()